schema_version: 1

context:
  version: "2.2.0"

package:
  name: python-lmdb
  version: ${{ version }}

source:
  url: https://github.com/jnwatson/py-lmdb/archive/refs/tags/py-lmdb_${{ version }}.tar.gz
  sha256: 050f04fc9671e1e3a9871e06e5e5b09eb9624d6cad53f2f4c637bca5293d986b
  patches:
    - 0001-typedef-pid_t-on-win.patch

build:
  number: 1
  script: |
    export LDFLAGS="${LDFLAGS} -Wl,-u,pthread_atfork -l:libc_nonshared.a"
    ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

  skip:
    - not aarch64
    - match(python, "<3.14")

requirements:
  build:
    # Bring back cross-compilation for pcc64le
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: unix
      then: patch
  host:
    - python
    - setuptools
    - if: win
      then: patch-ng
    - pip
    - patchelf
  run:
    - python

tests:
  - files:
      source:
        - tests
    requirements:
      run:
        - pytest
    script:
      # Verify linkage
      - echo "==== LDD ===="
      - conda inspect linkages -p $PREFIX python-lmdb || true
      - ldd $PREFIX/lib/python*/site-packages/lmdb/*.so
      - ldd $SP_DIR/lmdb/*.so || true
      - echo "==== RPATH ===="
      - readelf -d $SP_DIR/lmdb/*.so | grep -i path || true
      # Check as_needed
      - echo "==== NEEDED ===="
      - readelf -d $PREFIX/lib/python3.14/site-packages/lmdb/cpython*.so | grep NEEDED
      - echo "nm -D $PREFIX/lib/python3.14/site-packages/lmdb/cpython*.so | grep atfork"
      - nm -D $PREFIX/lib/python*/site-packages/lmdb/cpython*.so | grep -E "atfork|register_atfork"
      # - echo "nm -D /lib/aarch64-linux-gnu/libpthread.so.0 | grep atfork"
      # - nm -D /lib/aarch64-linux-gnu/libpthread.so.0 | grep atfork  # runtime host
      # - nm -D $BUILD_PREFIX/$HOST/sysroot/lib64/libpthread.so.0 | grep atfork  # build sysroot
      # Test
      - pytest
  - python:
      imports:
        - lmdb

about:
  license: OLDAP-2.8
  license_file: LICENSE
  summary: Universal Python binding for the LMDB 'Lightning' Database
  description: |
    LMDB is a fast, memory-efficient, embedded key-value store (it does
    not require running an external daemon).
    With memory-mapped files, it has the read performance of a pure
    in-memory database while retaining the persistence of standard
    disk-based databases.
    python-lmdb is a Python binding for LMDB including a bundled
    version of LMDB.
  homepage: https://lmdb.readthedocs.io/
  repository: https://github.com/jnwatson/py-lmdb
  documentation: https://lmdb.readthedocs.io/

extra:
  recipe-maintainers:
    - pitrou
    - h-vetinari
    - xhochy
